### ISSUE TITLE
Extra Life integration

### ISSUE THREAD

**Issue by andrejsavikin** [DoubleDoorDevelopment/Pay2Spawn#13]
I feel like this should be a thing, donate to charity. Destroy your fav. streamers. http://www.extra-life.org/ If you need any help with this, feel free to comment on this, I know a bit of java.
~Sava

**Comment by PoetPlays** [comment]
Is this what you're looking for? https://www.npmjs.com/package/extra-life-api
Seems third-party however.

**Comment by dries007** [comment]
We actually have Extra Life figured out, but you have to be careful when setting it up.
Basically you need to make sure you make 1 account (not a group / team) because there is no way to tracks the donations otherwise.
Its been a while though, so I can't be sure.
