### ISSUE TITLE
New way to spawn in entities

### ISSUE THREAD

**Issue by Claycorp** [DoubleDoorDevelopment/Pay2Spawn#25]
Instead of radial spawning we should add exact spawning. It works from the players coordinates and will spawn the mob in that location however many blocks away.
X = forwards
Y = up down
Z = ~~behind~~ left right?

Example: X1 Y0 Z0 This will spawn the mob one block in front of the player.

**Comment by PoetPlays** [comment]
I actually agree with this. People could design maps, with say a hopper, where items would always appear if things were donated to that user, even if they weren't in the area.

**Comment by Claycorp** [comment]
It would use the player X,Y,Z as a base for spawning things into unloaded areas wouldn't turn out well. This likely will not happen though as P2S isn't getting touched much anymore (outside of new trackers or major bugs) If there is an update to 1.8/1.9 you could do all of this via command blocks.
