### ISSUE TITLE
Player Modification: Health Subtract does nothing

### ISSUE THREAD

**Issue by KingNewbs** [DoubleDoorDevelopment/Pay2Spawn#38]
Heath Add, and Health Set work properly, but Subtract doesn't seem to do anything.

Yeah, it's me again.

Hope you kids are doing well :)

**Comment by Claycorp** [comment]
Oh mang...
It might be a bit before this can be fixed unless ya need it now. Working on something for someone else that needs to be done for this weekend.

**Comment by dries007** [comment]
try add with a negative value, that might work

2015-06-11 0:40 GMT+02:00 Claycorp <notifications@github.com>:

**Comment by KingNewbs** [comment]
Nah, it's not important. I can come up with other ways to do the thing I'm doing. Just reporting it for you.

I tried Add with a negative value, Dries, didn't do anything.

**Comment by Claycorp** [comment]
there's always instant damage potions! :P

**Comment by KingNewbs** [comment]
Exactly :)

**Comment by Claycorp** [comment]
Let us know if ya need anything else!
