### ISSUE TITLE
SSL issue for streamtip.

### ISSUE THREAD

**Issue by Claycorp** [DoubleDoorDevelopment/Pay2Spawn#39]
http://pastebin.com/ViHByjPJ
PotatoOrgy was having this issue. I don't know of any other streamtip users to test with to see if it's local or not. Perhaps you know more.

**Comment by dries007** [comment]
From [StackOverflow](http://stackoverflow.com/a/6353956)

> In most cases, this is because the root CA's certificate is absent in the trust store, leading to the situation where a certificate trust path cannot exist; the certificate is essentially untrusted by the client. Browsers can present a warning so that users may ignore this, but the same is not the case for SSL clients (like the HttpsURLConnection class, or any HTTP Client library like Apache HttpComponents Client).

Aka he's computer does not trust the certificate. It may be invalid, close to expiring.
OR his antivirus is intercepting the connection and tries to apply its own certificate to the connection. If that certificate isn't accepted by java, it will fail. Perhaps adding an exception to not scan `https://streamtip.com/api/tips?*`

**Comment by Claycorp** [comment]
Alright. Ill tell him.
