### ISSUE TITLE
This site needs to be supported

### ISSUE THREAD

**Issue by Chaosflo44** [DoubleDoorDevelopment/Pay2Spawn#41]
https://www.tipeeestream.com/

It's a donation site most of the german minecraft streamers use when streaming. I use this site as well and I'd like to include Pay2Spawn in my modpack so my viewers can contribute. Would love to see this site being supported in this mod.

**Comment by Claycorp** [comment]
API documentation: https://api.tipeeestream.com/api-doc/

This will be needed if its posible to add. It will be looked into!

**Comment by PoetPlays** [comment]
It should be noted, as an aside to the above, that there are even streaming services listed in the cfg now that are defunct or nonexistent such as supportthestream. The entire list needs a once-over.

**Comment by dries007** [comment]
If / when we update to 1.8 / 1.9, new sites will be added and old ones will be removed. (the whole mod is getting a do-over)
This site may still be added if I need to work on p2s in another capacity.

**Comment by simrom** [comment]
http://www.donationalerts.ru
Can you add this one? Most popular donation system in Russian Federation. Thx

**Comment by dries007** [comment]
I can't speak russian, and google translate is not nearly enough to develop something like this. If they have English support or information maybe.
