### ISSUE TITLE
Default to server JSON spawning groups

### ISSUE THREAD

**Issue by PoetPlays** [DoubleDoorDevelopment/Pay2Spawn#42]
By default, the mod is installed with a JSON file containing only the template group items (ie: rick rolling the user, spawning in various blocks, etc) once it is run on a client or server.

This is an issue in a server environment where people connecting pull from the server config file (as set in options). It seems to ignore the server JSON file if they already have one, and spawn in their own custom items.

For example: A user who has the mod installed and has $2 item set to zombies and a second user who has the mod installed and has a $2 item as skeletons, in the server environment the zombie and skeletons would spawn in rather than the one reflected on the server.

If a user doesn't have a $2 item, it falls back to the server option, but if they DO have a $2 item, those things spawn in.

With all of this said, since the template item is such a low donation amount, we quickly saw that when someone had only the default JSON installed, a bunch of things were spawning in around that user that weren't set up on the server.

So two possible fixes: Either have clients connected ignore their individual JSON files completely, or at the very least set the template item to an obscure donation amount such as "12346" or some such thing to avoid accidental spawning of items on users who choose not to change their JSON file to the one on the server.

**Comment by Claycorp** [comment]
Personally I have never ran into issues with using forced server configs. Though we normally use a different version of P2S that built a bit differently than the normal one.
I will set up a server to test this with and see if its reproducible. Other than that you could give everyone the file to avoid the issue.

**Comment by dries007** [comment]
The way the regular pay2spawn works is the rewards are determined by the client and the client alone.
(Since the client is the one who makes connection to the API's and stuff)

There is a version of p2s (called 'experimental' or 'serverside') in which everything is done by the server. If you want help setting up the server side version (it has little documentation, we use it internally for charity events) don't hesitate to message or reply.

-- Seems I got sniped
