### ISSUE TITLE
API key necessary for all server users

### ISSUE THREAD

**Issue by PoetPlays** [DoubleDoorDevelopment/Pay2Spawn#43]
In a server environment, unless each user has the same config file with the same API key (not very secure) installed, the items spawned in choose a seemingly random target, and only spawn in for that target.

For example: If user 1 has the cfg with API key to twitchalerts, donations will spawn things around that user. If user 2 has the cfg pulling from the server but DOES NOT have the API key in their own personal config, it will not spawn items around that user.

I believe that the items should pull the API key from the server cfg, and then split between online users post stream service polling rather than choosing only a single user to spawn at random... 

Our example is based on charity events we've hosted where multiple streamers are active on the same server, and multiple punishments or benefits are provided to EACH USER on the server. To do this, we have to install the API key on every single client for every single user that connects to the server. This is an extra step we'd rather avoid.

**Comment by Claycorp** [comment]
I think this was covered well in #42 'Normal' P2S isn't built for multiple people. It only supports one user and that's it. You will want to use the other version for things like this.

It can only be found here: http://www.doubledoordev.net/?p=modlist&mod=Pay2Spawn-EXPERIMENTAL

Again, If you need help setting it up let us know. There is no documentation for this beyond whats in the config file for how to get it to work. It still uses the same JSON stuff for the rewards though.

**Comment by dries007** [comment]
I can probably make a config option to not pick out one person, but instead target all online players.
(For Experimental that is)
