### ISSUE TITLE
[1.10.2] Streamjar (tracker) + Curseforge

### ISSUE THREAD

**Issue by MysticAura** [DoubleDoorDevelopment/Pay2Spawn#45]
[StreamJar ](https://streamjar.tv)is an extremely popular way for streamers to add tracker overlays and get donations. I'm surprised it hasn't been mentioned yet. 

I'd also like to be able to get access to the 1.10.2 version of this mod via curse/twitch launcher whenever you get the chance. Thanks for your time.

**Comment by dries007** [comment]
You are successfully using the 1.10.2 version? *Congratulations* You seem to be the only one who can figure it out! If you have the spare time / energy, could you help us write up some docs?

- I currently don't have the time to add new trackers, but I'll to it asap.
- I'd rather not put the version on Curseforge before we have at least some basic docs.

**Comment by Sataana** [comment]
I actually have a version that has been modified to use with StreamJar (if I can find it somewhere) but you would have to get StreamJar to give you a custom API key (with the new SJ Beta)

**Comment by dries007** [comment]
If @EthanWaite (or anyone in control of the StreamJar fork) is willing to submit a PR, it will be pulled and official builds will be made available.

(Preferably for both the old and new v3 branches)

**Comment by EthanWaite** [comment]
@dries007 Yep sure, I can tidy up some of the auth stuff and PR it in. Our server does use socket.io for realtime communication though (so donations come through instantly), and so our fork uses the socket.io Java library. Would adding a dependency for a tracker be an issue?

**Comment by dries007** [comment]
Thats fine, as long as it gets downloaded via gradle and is packaged in the download (fat jar style)
