### ISSUE TITLE
TwitchAlerts

### ISSUE THREAD

**Issue by fastkill3r** [DoubleDoorDevelopment/Pay2Spawn#9]
Would it be possible for http://www.twitchalerts.com/ to be added to the supported list of website trackers?

Thank you greatly for your time, and effort for this amazing mod <3

**Comment by Faella** [comment]
Is there something new about TwitchAlert ? Would love to use this mod, but won't change my donation settings.

**Comment by Claycorp** [comment]
We do have the information for Twitch Alerts it just needs to be implemented. Also we were told that it will be updating at some point in the near future so it likely will require another update by us when this happens.

**Comment by Faella** [comment]
That's really nice ! And fast answer O.O

Huge thanks for your job !

**Comment by Claycorp** [comment]
E-mail alerts :P 
If ya need any help getting stuff set up feel free to contact me!

**Comment by Faella** [comment]
Should be ok, just waiting for the TwitchAlert stuff :p

**Comment by Claycorp** [comment]
Well it was added. The latest build (266) should have it but its untested as none of us use it... Go ahead and test report any issues back!

Have fun!
